version: "3"

services:
  app:
    container_name: react-tutorial-with-docker
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: {}